DATA = "../data/"
IMAGES = "../data/images/"
CROPPED_IMAGES = "../data/croppedImages/"
GRAYSCALE_IMAGES = "../data/grayscale/"
KERAS_IMAGES = "../data/kerasImages/"
KERAS_GRAYSCALE_IMAGES = "../data/kerasGrayscaleImages"
IMAGE_TABLE = "../data/imageInfo.csv"
MANIFEST = "../data/exportEDAD7358427A4809A106511DDDFECF08.xml"
